//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_ShippingDetail Tbl_ShippingDetail { get; set; }
    }
}
